version: '3.8'
services:

  mongo:
    image: mongo
    ports:
     - "27017:27017"
    volumes:
     - ./data:/data/db 

  backend:
    build: 
      context: ./server   # Specify the path to the directory containing the Dockerfile
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - mongo
    environment:
      - MONGO_URL=mongo:27017/Controller1

  frontend:
    build: 
      context: ./client   # Specify the path to the directory containing the Dockerfile for the frontend
      dockerfile: Dockerfile
    stdin_open: true
    ports:
      - "3002:3002"
    depends_on:
      - backend
