version: '3.8'
services:

  mongo:
    image: mongo
    ports:
     - "27017:27017"
    volumes:
     - ./data:/data/db 

  backend:
    build: 
      context: ./server   # Specify the path to the directory containing the Dockerfile
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    depends_on:
      - mongo
    environment:
      - MONGO_URL=mongo:27017/Controller2

  frontend:
    build: 
      context: ./client   # Specify the path to the directory containing the Dockerfile for the frontend
      dockerfile: Dockerfile
    stdin_open: true
    environment:
      - BASE_URL=8001
    ports:
      - "3003:3003"
    depends_on:
      - backend
